[book]
authors = ["Guangwei Li"]
language = "zh-Hans"
multilingual = false
create-missing = false
src = "src"
title = "liguwe's site"
description = "832 之书，liguwe.github.io,liguwe.site,liguwe's blog,liguwe's notes,liguwe's wiki,liguwe's site，liguwe's book，liguwe's blog , liguwe's books，Guangwei Li's Book，liguwe's blog，liguwe's book，liguwe's site， Guangwei Li's site ，Guangwei Li's Books， Guangwei Li's blog，李广卫, 李广卫的知识库、 李广卫的博客、李广卫的个人网站、李广卫的站点"

[build]
create-missing = false

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/liguwe"
edit-url-template = "https://github.com/liguwe/liguwe.github.io/blob/master/{path}"
cname = "liguwe.site"


[output.html.print]
enable = false     # include support for printable output
page-break = false # insert page-break after each chapter

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = false # 因为不支持中文搜索


[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 6
